#!/bin/sh
#
# A pre-commit hook script to compile the SVGs into PNGs of various sizes.
# Place in the ./png folder. Requires Inkscape to be installed and in the PATH.
# To enable this hook, call it from the ".git/hooks/pre-commit".

# Repo path
REPO_PATH=$(git rev-parse --show-toplevel)

# Images path
IMG_PATH="$REPO_PATH/img"

# Get a path to the SVGs
SVG_PATH="$IMG_PATH/svg"

# Get inkscape
INKSCAPE=$(which inkscape)

# The width of PNGs we would like to generate
WIDTHS="16 32 48 64 128 256 512 1024 2048"

# List of SVGS
SVGS=$(ls $SVG_PATH/*.svg)

# Loop through the widths create the folders for PNGS
for WIDTH in $WIDTHS
do
    WIDTH_FOLDER="$IMG_PATH/png/$WIDTH"

    # Create the folder
    mkdir -p "$WIDTH_FOLDER"

    # Loop through the SVGs
    for SVG in $SVGS
    do
        # Get the filename
        FILENAME=$(basename $SVG)

        # Get the name of the file without the extension
        FILENAME_NO_EXT=${FILENAME%.*}

        # Get the path to the PNG
        PNG_PATH="$WIDTH_FOLDER/$FILENAME_NO_EXT.png"

        # Create the PNG
        INKSCAPE --export-filename="$PNG_PATH" --export-type="png" --export-width="$WIDTH" "$SVG"
    done
done
